[package]
name = "life-of-boids"
version = "0.1.0"
authors = ["Pascal HAVÃ‰ <hpwxf@haveneer.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#imgui = "0.7.0"
glfw = "0.41.0"
